### ISSUE TITLE
[SB-27] Pin the current admin to the post creation page

### ISSUE THREAD

**Issue by Captain-Vorobey** [RUBYLNIK-training-center/smart-banking#35]
How it works now:
When we are in CRM and go to the post creation page
We can select an admin from the list

Expected Behavior:
When we are in CRM and go to the post creation page
This field will not exist

![image](https://user-images.githubusercontent.com/43318298/123328897-d603d580-d544-11eb-942c-4af720ea2d5a.png)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/43318298/123328941-e3b95b00-d544-11eb-9e8c-3a7dfa80f2ef.png)

**Comment by m3xq** [comment]
Done
